title: BIOENGR 167L - Bioengineering Laboratory (Fall 2018)
author: Aaron Meyer
email: your-email@domain.com
description: Class materials for Bioengineering 167L at UCLA.

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md
# 
theme: jekyll-theme-primer

baseurl: "/167L-materials"